### ISSUE TITLE
Figure out Timing/Size

### ISSUE THREAD

**Issue by ggertsen** [wangwenchuan4/CS2820#3]
So separate from the repo I fooled around with a copy of the code to see if I could fix the bugs and get everything up and running, and now I have a local copy that "runs" without any runtime/compilation errors: I didn't push it because it involved a whole lot of dumb debugging print statements and changing some things that might've been flat-out wrong on my part. But after a few hours of tinkering, we have something.

Right now, our code does the following:

Initially, it generates a new robot, fills up the inventory, makes an order. Then it sends a robot off to grab a shelf that has the ordered item on it, the robot grabs the shelf, and brings it to a picker. The picker then puts the item in a bin -- after this, there aren't any print statements, so I'm not sure if it's going through the belt properly or not. After the item is put into the bin, a new order is generated.

The robot, once the item has been removed, returns the shelf back to where it came from, and then goes home to its charger no matter what. I'm not sure if it actually "charges" or not, but it has to go back to the charger before it can process the next order. Once the robot gets to its charger, it then goes back out to find the next shelf and the process repeats itself.

So for the most part, we actually have this thing working, with a few kinks. There's some unrealistic things, but the simulation at least works at this point.

The one main thing I think we should consider for the project as a whole is what we should do for timing/warehouse size. Right now, the whole process from getting an order to having the order delivered to the Picker takes around 400 ticks. This is due to two things: the warehouse is 160 x 200 units, and a robot only moves 1 unit per tick. 

There are a few things we can do with this. One thing we can do is we can accept it, and just adjust for it everywhere else. For example, I was originally "restocking" shelves every 10 ticks. Now, every 500 ticks is probably a more reasonable thing to do.

Our other options are either make the robots move multiple units every tick (might be hard) or scaling down the size of the warehouse to make everything closer together (changing constant values).

I'm down to do whatever you guys think is best. We have a few days to finish up, and hopefully we're looking good going into the final stretch.

**Comment by wangwenchuan4** [comment]
How many ticks should we choose for the production class?  500 ticks?

**Comment by ggertsen** [comment]
I think it'll depend on how small we end up making our warehouse. The smaller we make it, the less ticks we'll need. Right now I think it's around 2000, but if we cut our warehouse size down to about a forth of its current size (or less), 500 would probably be appropriate.

**Comment by ggertsen** [comment]
Resized down to 1/4th of the original size after discussion in class today. We can probably decrease tick now too.
